<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="/css/common.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <h1>talks</h1>
        <div>talks to someone</div>
        <h2>auth</h2>
        input your name and onetime password.<br>
        <form action="/auth" method="post">
          <label>
            name : <input type="text" name="name" value="">
          </label>
          <label>
            one time password : <input type="password" name="onetime_password" value="">
          </label>
          <input type="submit" value="go">
        </form>
    </body>
</html>

