<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="/css/common.css" rel="stylesheet" type="text/css">
    </head>
    <body>
    	<header>
	        <h1>talks</h1>
    	    <div>talks to someone</div>
        	<nav>
			<a href="/<?= @$_SESSION["loginUser"] ? @$_SESSION["loginUser"] : @$user->name ?>">home</a>
			</nav>
		</header>
        your name is <?= isset($_SESSION["loginUser"]) ? $_SESSION["loginUser"] : 'guest' ?><br>
        this place is <?= $name ?><br />
        <div class="contents">
          <p>
           	<span><?= $contents->updated_at ?></span>
           	<span><?= $contents->content ?></span><br>
            <span>to <?= $contents->send_name ?></span>
          </p>
        <? if (@$_SESSION["loginUser"] === $name): ?>
          <form action="/<?= $_SESSION["loginUser"] ?>/<?= $contents->id ?>" method="post">
            <input type="hidden" name="userId" value="<?= $_SESSION["userId"] ?>">
            <input type="hidden" name="_METHOD" value="delete">
            <input type="submit" value="delete">
          </form>
        <? endif ?>

        </div>
        <footer>
        <? if (isset($_SESSION["loginUser"])): ?>
        	<a href="/logout">logout</a>
        <? else: ?>
          <a href="/">top</a>
        <? endif ?>
        </footer>
    </body>
</html>
