<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="/css/common.css" rel="stylesheet" type="text/css">
    </head>
    <body>
        <h1>talks</h1>
        <div>talks to someone</div>
        <h1>login</h1>
        <form action="/login" method="post">
          <label>
            E-mail : <input type="email" name="email" value="">
          </label>
          <label>
            password : <input type="password" name="password" value="">
          </label>
          <input type="submit" value="login">
        </form>
    </body>
</html>
