<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="/css/common.css" rel="stylesheet" type="text/css">
    </head>
    <body>
    	<header>
	      <h1>talks</h1>
    	  <div>talks to someone</div>
      	<nav>
          <a href="/<?= @$_SESSION["loginUser"] ? @$_SESSION["loginUser"] : @$user->name ?>">home</a>
          <form action="/search" method="get">
            <input type="text" name="q" value="<?= @$_GET['q'] ?>">
            <input type="submit" value="search">
          </form>
  		</nav>
  		</header>
        your name is <?= isset($_SESSION["loginUser"]) ? $_SESSION["loginUser"] : 'guest' ?><br>
        <div class="contents">
        <? foreach (@$contents ?: array() as $content): ?>
          <p>
           	<span><?= $content->updated_at ?></span>
           	<span><a href="/<?= $content->user_name ?>/<?= $content->id ?>"><?= $content->content ?></a></span><br>
            <span>to <?= $content->send_name ?></span>
          </p>
	      <? endforeach ?>
        </div>
        <div class="pager">
        <? if ($offset > 0): ?>
          <a href="?q=<?= @$_GET['q'] ?>&offset=<?= $offset - 1 ?>">pre</a>
        <? endif ?>
        <? if ($contents !== NUll): ?>
          <a href="?q=<?= @$_GET['q'] ?>&offset=<?= $offset + 1 ?>">next</a>
        <? endif ?>
        </div>
        <footer>
        <? if (isset($_SESSION["loginUser"])): ?>
        	<a href="/logout">logout</a>
        <? else: ?>
          <a href="/">top</a>
        <? endif ?>
        </footer>
    </body>
</html>
