<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="/css/common.css" rel="stylesheet" type="text/css">
        <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
        <script src="/js/talks/speech.js"></script>
    </head>
    <body>
    	<header>
	      <h1>talks</h1>
    	  <div>talks to someone</div>
      	<nav>
          <a href="/<?= @$_SESSION["loginUser"] ? @$_SESSION["loginUser"] : @$user->name ?>">home</a>
          <form action="/search" method="get">
            <input type="text" name="q">
            <input type="submit" value="search">
          </form>
		  </nav>
		  </header>
        your name is <?= isset($_SESSION["loginUser"]) ? $_SESSION["loginUser"] : 'guest' ?><br>
        this place is <?= $name ?><br />
        <? if (@$_SESSION["loginUser"] === $name): ?>
        <form action="/user" method="post">
          <label>
      		 	talks : <input type="text" name="content" value="" id="result_text">
          </label>
          <label>
            to : <input type="text" name="to" value="<?= @$contents[0]->send_name ?>">
          </label>
          <input type="button" onClick="record()" value="録音開始" />
          <input type="submit" value="talks to">
        </form>
          <? if (@$_GET['error'] === 'user'): ?>
            <p>there is no user</p>
          <? endif ?>
          <? if (@$_GET['error'] === 'content'): ?>
            <p>please input talk message</p>
          <? endif ?>
        <? endif ?>
        <div class="contents">
        <? foreach (@$contents ?: array() as $content): ?>
          <p>
           	<span><?= $content->updated_at ?></span>
           	<span><a href="/<?= $name ?>/<?= $content->id ?>"><?= $content->content ?></a></span><br>
           	<span>from <a href="<?= $content->user_name ?>"><?= $content->user_name ?></a></span>
            <span>to <a href="/<?= $content->send_name ?>"><?= $content->send_name ?></a></span>
          </p>
        <? if (@$_SESSION["loginUser"] === $name): ?>
          <form action="/<?= $_SESSION["loginUser"] ?>/<?= $content->id ?>" method="post">
            <input type="hidden" name="userId" value="<?= $_SESSION["userId"] ?>">
            <input type="hidden" name="_METHOD" value="delete">
            <input type="submit" value="delete">
          </form>
        <? endif ?>
	      <? endforeach ?>
        </div>
        <div class="pager">
        <? if ($offset > 0): ?>
	        <a href="?offset=<?= $offset - 1 ?>">pre</a>
	    <? endif ?>
	    <? if ($contents !== NUll): ?>
	        <a href="?offset=<?= $offset + 1 ?>">next</a>
	    <? endif ?>
        </div>
        <footer>
        <? if (isset($_SESSION["loginUser"])): ?>
        	<a href="/logout">logout</a>
        <? else: ?>
          <a href="/">top</a>
        <? endif ?>
        </footer>
    </body>
</html>
