<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href="/css/common.css" rel="stylesheet" type="text/css">
    </head>
    <body>
    	<header>
	        <h1>talks</h1>
    	    <div>talks to someone</div>
        	<nav>
			<a href="/<?= @$user->name ?>">home</a>
			</nav>
		</header>
        your name is <?= isset($_SESSION["loginUser"]) ? $_SESSION["loginUser"] : 'guest' ?><br>
        this place is <?= $name ?><br />
        <? if (@$_SESSION["loginUser"] === $name): ?>
        <form action="/user" method="post">
          <label>
      		 	talks : <input type="text" name="content" value="">
          </label>
          <label>
            to : <input type="text" name="to" value="">
          </label>
          <input type="submit" value="talks to">
        </form>
        <? endif ?>
        <div class="contents">
        <? foreach ($contents as $content): ?>
          <p>
           	<span><?= $content->updated_at ?></span>
           	<span><?= $content->content ?></span><br>
            <span>to <?= $content->send_name ?></span>
          </p>
	     <? endforeach ?>
        </div>
        <footer>
        <? if (isset($_SESSION["loginUser"])): ?>
        	<a href="/logout">logout</a>
        <? else: ?>
          <a href="/">top</a>
        <? endif ?>
        </footer>
    </body>
</html>
